eapmaster:
  image: rsoares/centos7-eap6
  command: domain --host-config=host-master.xml --master-address=localhost
  volumes:
   - /etc/timezone:/etc/timezone:ro
   - /tmp/share:/tmp/share
  privileged: true
  hostname: master
